# -*-codeing = utf-8 -*-
# DDIN: Domain-aware Disentangled Interaction Network for Multimodal Fake News Detection

"""
Split & leakage audit for the three datasets used by DDIN.

Checks, per dataset:
  1. row counts and label/domain distribution per split
  2. exact text overlap (normalized-hash) between train/val/test
  3. shared image identifiers between splits (possible visual leakage)
  4. FineFake: conformity with the paper's 6:2:2 protocol

Exit code 1 if any FAIL-level leakage is found.

Usage:  python utils/check_splits.py
"""

import os
import sys
import hashlib
import pandas as pd

FAIL = "FAIL"
WARN = "WARN"
OK = "OK"


def norm_hash(text):
    t = "".join(str(text).split()).lower()
    return hashlib.md5(t.encode("utf-8")).hexdigest()


def image_tokens(series):
    """Flatten weibo-style 'a.jpg|b.jpg|' image_id columns into a set."""
    tokens = set()
    for cell in series.dropna().astype(str):
        for tok in cell.split("|"):
            tok = tok.split("/")[-1].split(".")[0].strip().lower()
            if tok:
                tokens.add(tok)
    return tokens


def report(status, msg, findings):
    findings.append(status)
    print(f"  [{status}] {msg}")


def audit_splits(name, splits, text_col, findings, image_col=None, id_col=None):
    print(f"\n=== {name} ===")
    frames = {}
    for split_name, df in splits.items():
        if df is None:
            print(f"  [{WARN}] {split_name}: file missing, skipped")
            return
        frames[split_name] = df
        label_info = ""
        if "label" in df.columns:
            vc = df["label"].astype(int).value_counts().to_dict()
            label_info = f", labels={vc}"
        print(f"  {split_name}: {len(df)} rows{label_info}")

    names = list(frames.keys())
    for i in range(len(names)):
        for j in range(i + 1, len(names)):
            a, b = names[i], names[j]
            da, db = frames[a], frames[b]

            # 1) exact text overlap
            ha = set(da[text_col].map(norm_hash))
            hb = set(db[text_col].map(norm_hash))
            inter = ha & hb
            if inter:
                report(FAIL, f"{a}/{b}: {len(inter)} identical texts shared across splits "
                             f"(text leakage)", findings)
            else:
                report(OK, f"{a}/{b}: no identical texts", findings)

            # 2) id overlap
            if id_col and id_col in da.columns and id_col in db.columns:
                ia = set(da[id_col].astype(str))
                ib = set(db[id_col].astype(str))
                if ia & ib:
                    report(FAIL, f"{a}/{b}: {len(ia & ib)} shared {id_col} values", findings)
                else:
                    report(OK, f"{a}/{b}: no shared {id_col}", findings)

            # 3) image overlap
            if image_col and image_col in da.columns and image_col in db.columns:
                ga = image_tokens(da[image_col])
                gb = image_tokens(db[image_col])
                shared = ga & gb
                if shared:
                    report(WARN, f"{a}/{b}: {len(shared)} images appear in both splits "
                                 f"(same image reused across posts - known property of the "
                                 f"source benchmark, treat with care)", findings)
                else:
                    report(OK, f"{a}/{b}: no shared images", findings)


def load_csv(path):
    return pd.read_csv(path) if os.path.exists(path) else None


def load_xlsx(path):
    return pd.read_excel(path) if os.path.exists(path) else None


def main():
    findings = []

    # ---- Weibo (Jin et al. MM'17 benchmark split, as used by EANN/CAFE/MCAN line) ----
    weibo = {
        "train": load_csv("data/train_origin.csv"),
        "val": load_csv("data/val_origin.csv"),
        "test": load_csv("data/test_origin.csv"),
    }
    text_col = "content" if weibo["train"] is None or "content" in weibo["train"].columns else "text"
    audit_splits("Weibo (official benchmark split files)", weibo, text_col, findings,
                 image_col="image_id", id_col="post_id")

    # ---- Weibo21 (official MDFEND-Weibo21 split) ----
    w21 = {
        "train": load_xlsx("weibo21/train_datasets.xlsx"),
        "val": load_xlsx("weibo21/val_datasets.xlsx"),
        "test": load_xlsx("weibo21/test_datasets.xlsx"),
    }
    audit_splits("Weibo21 (official MDFEND-Weibo21 split)", w21, "content", findings,
                 image_col="image")

    # ---- FineFake (paper 6:2:2 protocol, generated by utils/fsplit.py) ----
    ff = {
        "train": load_csv("FineFake/train.csv"),
        "val": load_csv("FineFake/val.csv"),
        "test": load_csv("FineFake/test.csv"),
    }
    audit_splits("FineFake (6:2:2 protocol)", ff, "text", findings, image_col="image_path")

    if all(df is not None for df in ff.values()):
        total = sum(len(df) for df in ff.values())
        ratios = {k: len(df) / total for k, df in ff.items()}
        print(f"  ratios: train={ratios['train']:.3f}, val={ratios['val']:.3f}, "
              f"test={ratios['test']:.3f} (paper protocol: 0.6/0.2/0.2)")
        if abs(ratios["train"] - 0.6) > 0.02 or abs(ratios["val"] - 0.2) > 0.02:
            report(FAIL, "FineFake split ratio deviates from the paper's 6:2:2 protocol", findings)
        else:
            report(OK, "FineFake split ratio matches 6:2:2", findings)
        if os.path.exists("FineFake/FineFake.pkl"):
            full = pd.read_pickle("FineFake/FineFake.pkl")
            print(f"  FineFake.pkl total: {len(full)}, splits total: {total} "
                  f"(difference = rows with empty text, dropped by fsplit.py)")

    print("\n=== SUMMARY ===")
    n_fail = findings.count(FAIL)
    n_warn = findings.count(WARN)
    if n_fail:
        print(f"{n_fail} FAIL, {n_warn} WARN - fix the FAIL items before training.")
        sys.exit(1)
    print(f"0 FAIL, {n_warn} WARN - splits are consistent with the source papers.")


if __name__ == "__main__":
    main()

# Author:
# Corresponding Mail:
